apiVersion: v1
kind: Pod
metadata:
  name: word-picker-with-pullsecret
  labels: 
    app: word-picker
    custom: "yes"
spec:
  containers:
  - image: tinmancoding/word-picker:v1
    name: word-picker
    imagePullPolicy: Always
  imagePullSecrets:
  - name: dockerhub


